server {
    listen 80;
    server_name guba.dev www.guba.dev;
    root /usr/share/nginx/html;
    index index.html;

    location = /blog { return 301 /blog/; }
    location /blog/ {
        alias /usr/share/nginx/html/blog/;
        index index.html;
    }

    location = /projects { return 301 /projects/; }
    location /projects/ {
        alias /usr/share/nginx/html/projects/;
        index index.html;
    }
}
