name: Deploy Monorepo
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Tell Git to trust this folder
            git config --global --add safe.directory /var/www/html

            cd /var/www/html

            if [ ! -d ".git" ]; then
              git init
              git remote add origin git@github.com:PatrickGM1/guba-dev-site.git
            fi

            # Use the token for the fetch
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/PatrickGM1/guba-dev-site.git

            git fetch --all
            git reset --hard origin/main

            chown -R www-data:www-data /var/www/html
            chmod -R 755 /var/www/html
